@host = localhost
@port = 3030
@uriBase = http://{{host}}:{{port}}
@uri = {{uriBase}}
@uriDb = {{uriBase}}/db
@uriSurrealDb = {{uriBase}}/surrealdb
@uriGql = {{uriBase}}/graphql
@contentType = application/json

@thing = person:uv1o55sjes0tdpa31ool
@thingTobie = person:tobie
@thingRestaurant = restaurant:a6
@thingRecipe = recipe:a1
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NjI3NjE5MTUsIm5iZiI6MTY2Mjc2MTkxNSwiZXhwIjoxNjYzOTcxNTE1LCJpc3MiOiJTdXJyZWFsREIiLCJucyI6InRlc3QiLCJkYiI6InRlc3QiLCJzYyI6ImFsbHVzZXJzIiwiaWQiOiJ1c2VyOjB3aGdnZHdna205d2w2aDY4emxjIn0.-bLrZge6Xqm6xTG5Zdp08Suvyrn-vOMJDu12m9kduDhRt7rrW0V2n_4mQYk8ey6UTxtOAktHNpPNzDyZkq3qKg

// ::::: BO app-rst :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

// local AppModule:AppController

### getHello
// @name getHello
GET {{uri}} HTTP/1.1
Content-Type: {{contentType}}

### appLib SurrealDbModule

### getConfig
// @name getConfig
// call surrealDbService.getConfig()

GET {{uri}}/config HTTP/1.1
Content-Type: {{contentType}}

{
}

### getHelloAppModule
// @name getHelloAppModule
// call surrealDbService.getHelloAppModule()

GET {{uri}}/appservice HTTP/1.1
Content-Type: {{contentType}}

{
}

### getUserFindOneByField
// @name getUserFindOneByField
// call surrealDbService.getUserFindOneByField()

GET {{uri}}/userservice HTTP/1.1
Content-Type: {{contentType}}

{
}

// local AppModule:DbModule: DbController

### getUserFindOneByFieldInsideDbModule
// @name getUserFindOneByFieldInsideDbModule
// call surrealDbService.getUserFindOneByField() (moked user)

GET {{uriDb}}/userservice HTTP/1.1
Content-Type: {{contentType}}

{
}

### getSelectDbModule
// @name getSelectDbModule
// call surrealDbService.select(thing)

GET {{uriDb}}/select/{{thing}}
Content-Type: application/json

// ::::: EO app-rst :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

// ::::: BO app-rst and app-gql :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

###  surrealDbModule: surrealDb proxy methods

### postConnect
// @name postConnect

POST {{uriSurrealDb}}/connect
Content-Type: application/json

{
  "url": "http://127.0.0.1:8000/rpc"
}

### postClose
// @name postClose

POST {{uriSurrealDb}}/close
Content-Type: application/json

{
}

### postUse
// @name postUse

POST {{uriSurrealDb}}/use
Content-Type: application/json

{
  "ns": "test",
  "db": "test"
}

### postSignup
// @name postSignup

POST {{uriSurrealDb}}/signup
Content-Type: application/json

{
  "ns": "test",
  "db": "test",
  // We want to signup to the 'allusers' scope defined above
  "sc": "allusers",
  // We can add any variable here to use in the SIGNUP clause
  // "email": "tobie@surrealdb.com",
  "user": "tobie",
  // We can add any variable here to use in the SIGNUP clause
  "pass": "some password",
  // We can add any variable here to use in the SIGNUP clause
  "marketing": true,
  // We can add any variable here to use in the SIGNUP clause
  "tags": ["rust", "golang", "javascript"]
}

### postSignin
// @name postSignin

POST {{uriSurrealDb}}/signin
Content-Type: application/json

{
  "ns": "test",
  "db": "test",
  // We want to signup to the 'allusers' scope defined above
  "sc": "allusers",
  // We can add any variable here to use in the SIGNUP clause
  // "email": "tobie@surrealdb.com",
  "user": "tobie",
  // We can add any variable here to use in the SIGNUP clause
  "pass": "some password"
}

### postInvalidate
// @name postInvalidate

POST {{uriSurrealDb}}/invalidate
Content-Type: application/json

{
}

### postAuthenticate
// @name postAuthenticate
// TODO: how authenticate?

POST {{uriSurrealDb}}/authenticate
Content-Type: application/json

{
  "token": "{{token}}"
}

### postLet
// @name postLet

POST {{uriSurrealDb}}/let
Content-Type: application/json

{
  "key": "name",
  "value": {
    "name": {
      "first": "Tobie",
      "last": "Morgan Hitchcock"
    }
  }
}

### postQuery
// @name postQuery

POST {{uriSurrealDb}}/query
Content-Type: application/json

{
  "sql": "SELECT id, string::concat(name.first, ' ', name.last) AS name, age FROM $id;",
  "vars": {
    "id": "{{thing}}"
  }
  // "sql": "SELECT * FROM $auth"
  // "sql": "SELECT * FROM $session"
  // "sql": "SELECT * FROM $scope"
}

### getSelect
// @name getSelect

GET {{uriSurrealDb}}/select/{{thing}}
Content-Type: application/json

### postCreate
// @name postCreate

POST {{uriSurrealDb}}/create/{{thing}}
Content-Type: application/json

{
  "title": "Founder & CEO",
  "name": {
    "first": "Tobie",
    "last": "Morgan Hitchcock"
  },
  "marketing": true,
  "age": 28,
  "html":"123"
}

### putUpdate
// @name putUpdate
// replace current record with payload data
// TODO: BadRequestException : Bad Request Exception

PUT {{uriSurrealDb}}/update/{{thing}}
Content-Type: application/json

{
  "name": {
    "first": "Mário",
    "last": "Monteiro"
  },
  "age": 50,
  "country": "Portugal"
}

### patchChange
// @name patchChange
// patches thing, update only sent properties leaving all others untoutched
// TODO: BadRequestException : Bad Request Exception

PATCH {{uriSurrealDb}}/change/{{thing}}
Content-Type: application/json

{
  "name": {
    "first": "Tobie changed...",
    "last": "Morgan Hitchcock changed..."
  }
}

### patchModify
// @name patchModify
// modify replaces properties of record

PATCH {{uriSurrealDb}}/modify/{{thing}}
Content-Type: application/json

{
  "name": {
    "fullName": "Tobie Morgan Hitchcock"
  }
}

### deleteDelete
// @name deleteDelete

DELETE {{uriSurrealDb}}/delete/{{thing}}
Content-Type: application/json

### postSync
// @name postSync
// TODO: sync, live, and kill aren't fully implemented yet

POST {{uriSurrealDb}}/sync
Content-Type: application/json

{
}

### postPing
// @name postPing
// ping is used internally. It doesn't need to be called from any client code

POST {{uriSurrealDb}}/ping
Content-Type: application/json

{
}

### postInfo
// @name postInfo

POST {{uriSurrealDb}}/info
Content-Type: application/json

{
}

### postLive
// @name postLive
// TODO: sync, live, and kill aren't fully implemented yet

POST {{uriSurrealDb}}/live
Content-Type: application/json

{
}

### postKill
// @name postKill
// TODO: sync, live, and kill aren't fully implemented yet

POST {{uriSurrealDb}}/kill
Content-Type: application/json

{
}


// ::::: EO app-rst and app-gql :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

// ::::: BO app-gql :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

@requestType = GraphQL
@random = {{$randomInt 1000 9999}}

## restaurants

### mutation: createRestaurant
// @name createRestaurant
POST {{uriGql}} HTTP/1.1
Content-Type: {{contentType}}
X-REQUEST-TYPE: {{requestType}}
// Authorization: Bearer {{authToken}}

mutation createRestaurant($createRestaurantInput: CreateRestaurantInput!) {
	createRestaurant(createRestaurantInput: $createRestaurantInput) {
    id
    uuid
    name
    description
    email
    recipes {
      id
      title
      description
      ingredients
      createdAt
      updatedAt
    }
    createdAt
    updatedAt
	}
}

{
	"createRestaurantInput": {
    "id": "{{thingRestaurant}}",
    "uuid": "{{$guid}}",
    "name": "Restaurant #{{random}}",
    "description": "some description #{{random}}",
    "email": "fake@email.com"
    // TODO: use surrealId here, and check if exists
    // "recipes": ["bananas", "apples", "lemons", "pears"]
  }
}

### mutation: updateRestaurant
// @name updateRestaurant

POST {{uriGql}} HTTP/1.1
Content-Type: {{contentType}}
X-REQUEST-TYPE: {{requestType}}
// Authorization: Bearer {{authToken}}

mutation updateRestaurant($id: String!, $updateRestaurantInput: UpdateRestaurantInput!) {
	updateRestaurant(id: $id, updateRestaurantInput: $updateRestaurantInput) {
    id
    uuid
    name
    description
    recipes {
      id
      title
      description
      ingredients
      createdAt
      updatedAt
    }
    createdAt
    updatedAt
	}
}

{
  "id": "{{thingRestaurant}}",
	"updateRestaurantInput": {
    "name": "Restaurant #{{random}}-MOD",
    "description": "some description #{{random}}-MOD"
    // TODO:
    // "ingredients": ["bananas", "apples", "lemons", "pears", "mod"]
  }
}

### query: findOneRestaurant
// @name findOneRestaurant

POST {{uriGql}} HTTP/1.1
Content-Type: {{contentType}}
X-REQUEST-TYPE: {{requestType}}
// Authorization: Bearer {{authToken}}

query findOneRestaurant($id: String!){
  findOneRestaurant(id: $id ){
    id
    uuid
    name
    description
    recipes {
      id
      title
      description
      ingredients
      createdAt
      updatedAt
    }
    createdAt
    updatedAt
  }
}

{
	"id": "{{thingRestaurant}}"
}

### query: findManyRestaurants
// @name findManyRestaurants

POST {{uriGql}} HTTP/1.1
Content-Type: {{contentType}}
X-REQUEST-TYPE: {{requestType}}
// Authorization: Bearer {{authToken}}

query findManyRestaurants($skip: Int, $take: Int) {
  findManyRestaurants(skip: $skip, take: $take) {
    id
    uuid
    name
    description
    recipes {
      id
      title
      description
      ingredients
      createdAt
      updatedAt
      # this test dataLoader working using same recipes from restaurants
      # if we opt to not use it in `async recipes(` we can comprove that we have a lot more queries against surrealdb
      restaurant {
        id
        recipes {
          id
        }
      }
    }
    createdAt
    updatedAt
  }
}

{
	"skip": 0,
  "take": 10
}

### mutation: removeRestaurant
// @name removeRestaurant

POST {{uriGql}} HTTP/1.1
Content-Type: {{contentType}}
X-REQUEST-TYPE: {{requestType}}
// Authorization: Bearer {{authToken}}

mutation removeRestaurant($id: String!){
  removeRestaurant(id: $id )
}

{
  "id": "{{thingRestaurant}}"
}

### subscription: restaurantAdded
// @name restaurantAdded

POST {{uriGql}} HTTP/1.1
Content-Type: {{contentType}}
X-REQUEST-TYPE: {{requestType}}
// Authorization: Bearer {{authToken}}

subscription restaurantAdded{
  restaurantAdded{
    id
    name
  }
}

### subscription: restaurantUpdated
// @name restaurantUpdated

POST {{uriGql}} HTTP/1.1
Content-Type: {{contentType}}
X-REQUEST-TYPE: {{requestType}}
// Authorization: Bearer {{authToken}}

subscription restaurantUpdated{
  restaurantUpdated{
    id
    name
  }
}

### subscription: restaurantDeleted
// @name restaurantDeleted

POST {{uriGql}} HTTP/1.1
Content-Type: {{contentType}}
X-REQUEST-TYPE: {{requestType}}
// Authorization: Bearer {{authToken}}

subscription restaurantDeleted{
  restaurantDeleted
}

### recipes

### mutation: createRecipe
// @name createRecipe
POST {{uriGql}} HTTP/1.1
Content-Type: {{contentType}}
X-REQUEST-TYPE: {{requestType}}
// Authorization: Bearer {{authToken}}

mutation createRecipe($createRecipeInput: CreateRecipeInput!) {
	createRecipe(createRecipeInput: $createRecipeInput) {
    id
    uuid
    title
    description
    ingredients
    restaurant{
      id
      name
      recipes {
        id
        title
        description
        ingredients
        createdAt
        updatedAt
      }
    }
    createdAt
    updatedAt
	}
}

{
	"createRecipeInput": {
    "id": "{{thingRecipe}}",
    "restaurant": "{{thingRestaurant}}",
    "uuid": "{{$guid}}",
    "title": "Recipe #{{random}}",
    "description": "some description #{{random}}",
    "ingredients": ["bananas", "apples", "lemons", "pears"]
  }
}

### mutation: updateRecipe
// @name updateRecipe

POST {{uriGql}} HTTP/1.1
Content-Type: {{contentType}}
X-REQUEST-TYPE: {{requestType}}
// Authorization: Bearer {{authToken}}

mutation updateRecipe($id: String!, $updateRecipeInput: UpdateRecipeInput!) {
	updateRecipe(id: $id, updateRecipeInput: $updateRecipeInput) {
    id
    uuid
    title
    description
    ingredients
    createdAt
    updatedAt
	}
}

{
  "id": "{{thingRecipe}}",
	"updateRecipeInput": {
    "title": "Recipe #{{random}}-MOD",
    "description": "some description #{{random}}-MOD",
    "ingredients": ["bananas", "apples", "lemons", "pears", "mod"]
  }
}

### query: findOneRecipe
// @name findOneRecipe

POST {{uriGql}} HTTP/1.1
Content-Type: {{contentType}}
X-REQUEST-TYPE: {{requestType}}
// Authorization: Bearer {{authToken}}

query findOneRecipe($id: String!){
  findOneRecipe(id: $id ){
    id
    uuid
    title
    description
    ingredients
    restaurant {
      id
      name
    }
    createdAt
    updatedAt
  }
}

{
	"id": "{{thingRecipe}}"
}

### query: findManyRecipes
// @name findManyRecipes

POST {{uriGql}} HTTP/1.1
Content-Type: {{contentType}}
X-REQUEST-TYPE: {{requestType}}
// Authorization: Bearer {{authToken}}

query findManyRecipes($skip: Int, $take: Int) {
  findManyRecipes(skip: $skip, take: $take) {
    id
    uuid
    title
    description
    ingredients
    restaurant {
      id
      name
    }
    createdAt
    updatedAt
  }
}

{
	"skip": 0,
  "take": 10
}

### mutation: removeRecipe
// @name removeRecipe

POST {{uriGql}} HTTP/1.1
Content-Type: {{contentType}}
X-REQUEST-TYPE: {{requestType}}
// Authorization: Bearer {{authToken}}

mutation removeRecipe($id: String!){
  removeRecipe(id: $id )
}

{
  "id": "{{thingRecipe}}"
}

### subscription: recipeAdded
// @name recipeAdded

POST {{uriGql}} HTTP/1.1
Content-Type: {{contentType}}
X-REQUEST-TYPE: {{requestType}}
// Authorization: Bearer {{authToken}}

subscription recipeAdded{
  recipeAdded{
    id
    name
  }
}

### subscription: recipeUpdated
// @name recipeUpdated

POST {{uriGql}} HTTP/1.1
Content-Type: {{contentType}}
X-REQUEST-TYPE: {{requestType}}
// Authorization: Bearer {{authToken}}

subscription recipeUpdated{
  recipeUpdated{
    id
    name
  }
}

### subscription: recipeDeleted
// @name recipeDeleted

POST {{uriGql}} HTTP/1.1
Content-Type: {{contentType}}
X-REQUEST-TYPE: {{requestType}}
// Authorization: Bearer {{authToken}}

subscription recipeDeleted{
  recipeDeleted
}

// ::::: EO app-gql :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
